function rnd(d){return Math.floor(Math.random()*(d+1))}Array.prototype.remove=function(d){i=0;for(found=!1;i<this.length&&!found;)this[i]==d?(this.splice(i,1),found=!0):i++};var console;function setDebugEnv(d){console="#"+d}function debug(d){$(console).html(""+$(console).text()+d+"<br>")}var bubbleSilverImage,bubbleRedImage,bubbleOrangeImage,bubblePurpleImage,bubbleYellowImage,lvlFrame,backgroundImage,logoImage,game,fps=16,pointExplode=3,pointDrop=25;
function bubble(d){this.lvl=d;this.flavor="nula";this.marked=!1;this.y=this.x=this.j=this.i=-1;this.dy=this.dx=0;this.meinBild=new Image;this.makeItRandom=function(){switch(rnd(4)){case 0:this.flavor="silver";this.meinBild=bubbleSilverImage;break;case 1:this.flavor="yellow";this.meinBild=bubbleYellowImage;break;case 2:this.flavor="purple";this.meinBild=bubblePurpleImage;break;case 3:this.flavor="red";this.meinBild=bubbleRedImage;break;case 4:this.flavor="orange",this.meinBild=bubbleOrangeImage}};
this.move=function(){if(!(this.dx==0&&this.dy==0)){this.x+=this.dx;this.y+=this.dy;if(this.x<=this.lvl.leftBound||this.x>this.lvl.width)this.dx=-this.dx;this.y<=this.lvl.topBound&&this.stopMove()}};this.draw=function(d){d.drawImage(this.meinBild,this.x,this.y,this.lvl.bubbleRadius,this.lvl.bubbleRadius)};this.stopMove=function(){this.dy=this.dx=0};this.equalBubble=function(d){return d.flavor=this.flavor};this.recalcXY=function(){h=Math.sqrt(this.lvl.bubbleRadius*this.lvl.bubbleRadius-this.lvl.bubbleRadius/
2*(this.lvl.bubbleRadius/2));delta=this.lvl.grilla.isShortRow(this.i)*(this.lvl.bubbleRadius/2);this.x=this.j*this.lvl.bubbleRadius+delta;this.y=this.i*h;this.x+=this.lvl.leftBound;this.y+=this.lvl.topBound};this.recalcXYfrom=function(d){this.recalcXY();h=Math.sqrt(this.lvl.bubbleRadius*this.lvl.bubbleRadius-this.lvl.bubbleRadius/2*(this.lvl.bubbleRadius/2));y=d.i*h+this.lvl.topBound;this.y+=d.y-y};this.isMoving=function(){return this.dx!=0||this.dy!=0}}
function bubbleCannon(d){this.lvl=d;this.readyShoot=!1;this.shoot=function(d,f){if(this.readyShoot)vecx=d-this.lvl.left-(this.currentBubble.x+this.lvl.bubbleRadius/2),vecy=f-this.lvl.top-(this.currentBubble.y+this.lvl.bubbleRadius/2),hip=Math.sqrt(vecx*vecx+vecy*vecy),velocity=17,this.currentBubble.dx=velocity*(vecx/hip),this.currentBubble.dy=velocity*(vecy/hip),this.lvl.setShootedBubble(this.currentBubble),this.currentBubble=null};this.setReadyShoot=function(){this.currentBubble=new bubble(this.lvl);
this.currentBubble.makeItRandom();this.currentBubble.x=d.width/2-this.lvl.bubbleRadius/2+this.lvl.leftBound;this.currentBubble.y=d.height-d.bubbleRadius+this.lvl.topBound;this.readyShoot=!0}}
function bubbleTable(d,g,f){this.lvl=f;this.alto=g;this.ancho=d;this.Table=Array(this.alto);for(i=0;i<this.alto;++i)this.Table[i]=Array(this.ancho);for(i=0;i<this.alto;++i)for(j=0;j<this.ancho;++j)this.Table[i][j]="vacio";for(i=0;i<this.alto;++i)i%2==0&&(this.Table[i][this.ancho-1]="nada");this.touchedBubbles=[];this.retrieveBubble=function(a,e){if(a>=this.alto||a<0)return new bubble(this.lvl);if(e>=this.ancho||e<0)return new bubble(this.lvl);if(this.isShortRow(a)&&e==this.ancho)return new bubble(this.lvl);
return this.Table[a][e]};this.isShortRow=function(a){return this.Table[a][this.ancho-1]=="nada"?1:0};this.addBubble=function(a,e){radius=this.lvl.bubbleRadius/2;halfradius=radius/2;dy=dx=0;deltax=e.x-a.x;deltay=e.y-a.y;this.isShortRow(e.i)?(deltax>halfradius&&(dx=0),deltax<-halfradius&&(dx=1)):(deltax>halfradius&&(dx=-1),deltax<-halfradius&&(dx=0));deltay>-halfradius&&(dy=-1);deltay<halfradius&&(dy=1);a.i=e.i+dy;a.j=e.j+dx;this.Table[a.i][a.j]=a;a.recalcXYfrom(e);c=this.checkForCompatibility(a,a.flavor);
this.lvl.mutex=!0;c>=3?(this.lvl.pointsMultiplier=pointExplode,this.explodeMarked(),this.lvl.pointsMultiplier=pointDrop,this.checkForOrphans()):this.clearMarks();this.touchedBubbles=[];this.lvl.setReadyShoot()};this.checkForCompatibility=function(a,e){if(a=="nada"||a=="vacio")return 0;if(a.flavor=="nula")return 0;if(a.marked)return 0;this.touchedBubbles.push(a);a.marked=!0;return a.flavor==e?(c=1,c+=this.checkForCompatibility(this.retrieveBubble(a.i,a.j+1),e),c+=this.checkForCompatibility(this.retrieveBubble(a.i,
a.j-1),e),c+=this.checkForCompatibility(this.retrieveBubble(a.i-1,a.j),e),c+=this.checkForCompatibility(this.retrieveBubble(a.i+1,a.j),e),this.isShortRow(a.i)?(c+=this.checkForCompatibility(this.retrieveBubble(a.i+1,a.j+1),e),c+=this.checkForCompatibility(this.retrieveBubble(a.i-1,a.j+1),e)):(c+=this.checkForCompatibility(this.retrieveBubble(a.i+1,a.j-1),e),c+=this.checkForCompatibility(this.retrieveBubble(a.i-1,a.j-1),e)),c):(a.marked=!1,0)};this.checkNeighbours=function(a){if(a=="nada"||a=="vacio")return!0;
if(a.flavor=="nula")return!1;if(a.marked)return!0;c=(c=(c=(c=(c=a.marked=!0)&&this.checkNeighbours(this.retrieveBubble(a.i,a.j+1)))&&this.checkNeighbours(this.retrieveBubble(a.i,a.j-1)))&&this.checkNeighbours(this.retrieveBubble(a.i-1,a.j)))&&this.checkNeighbours(this.retrieveBubble(a.i+1,a.j));c=this.isShortRow(a.i)?(c=c&&this.checkNeighbours(this.retrieveBubble(a.i+1,a.j+1)))&&this.checkNeighbours(this.retrieveBubble(a.i-1,a.j+1)):(c=c&&this.checkNeighbours(this.retrieveBubble(a.i+1,a.j-1)))&&this.checkNeighbours(this.retrieveBubble(a.i-
1,a.j-1));return a.marked=c};this.checkForOrphans=function(){for(;this.touchedBubbles.length>0;)toCheck=this.touchedBubbles.shift(),this.checkNeighbours(toCheck)?this.explodeMarked():this.clearMarks()};this.explodeMarked=function(){for(var a=0;a<this.alto;++a)for(var e=0;e<this.ancho;++e)b=this.Table[a][e],b!="nada"&&b!="vacio"&&b.marked&&(this.lvl.removeBubble(b),this.Table[a][e]="vacio",this.touchedBubbles.remove(b))};this.clearMarks=function(){for(i=0;i<this.alto;++i)for(j=0;j<this.ancho;++j)if(this.Table[i][j]!=
"nada"||this.Table[i][j]!="vacio")b=this.Table[i][j],b.marked=!1}}
function bubbleLevel(d,g,f,a){this.grilla=new bubbleTable(f,a,this);this.width=d;this.height=g;this.mutex=!1;this.bubbleRadius=this.width/f;this.shootedBubble=null;this.bubbles_array=[];this.points=0;this.pointsToReach=1E3;this.pointsMultiplier=0;this.fallvelocity=0.2;this.bubbleVelocity=this.bubbleRadius*(this.fallvelocity/fps);this.fpscount=0;this.moveBalls=function(){this.fpscount++;this.fpscount=Math.round(this.fpscount%(fps/this.fallvelocity));this.fpscount==0&&this.addRandomRow();for(i=0;i<
this.bubbles_array.length;++i)this.bubbles_array[i].move();if(this.mutex!=!0&&this.shootedBubble!=null&&(this.shootedBubble.move(),this.shootedBubble!=null)){for(i=0;i<this.bubbles_array.length;++i)if(currentBubble=this.bubbles_array[i],disx=Math.abs(currentBubble.x-this.shootedBubble.x),disy=Math.abs(currentBubble.y-this.shootedBubble.y),distance=Math.sqrt(disx*disx+disy*disy),distance<this.bubbleRadius*0.9){this.mutex=!0;this.shootedBubble.stopMove();this.addBubble(this.shootedBubble);this.grilla.addBubble(this.shootedBubble,
currentBubble);this.shootedBubble.dy=this.bubbleVelocity;this.shootedBubble=null;this.mutex=!1;break}if(this.shootedBubble!=null&&!this.shootedBubble.isMoving())this.bubbles_array.push(this.shootedBubble),this.shootedBubble=null}};this.setShootedBubble=function(a){this.shootedBubble=a};this.drawBalls=function(a){for(i=0;i<this.bubbles_array.length;++i)this.bubbles_array[i].draw(a);this.shootedBubble!=null&&this.shootedBubble.draw(a)};this.addBubble=function(a){this.bubbles_array.push(a)};this.removeBubble=
function(a){for(var d=0;d<this.bubbles_array.length;++d)this.bubbles_array[d].i==a.i&&this.bubbles_array[d].j==a.j&&(this.bubbles_array.splice(d,1),this.addPoints())};this.setReadyShoot=function(){this.mutex=!1;this.cannon.setReadyShoot()};this.addPoints=function(){this.points+=this.pointsMultiplier};this.makeMeRandom=function(a){for(i=0;i<a;++i){isShort=this.grilla.isShortRow(i);for(j=0;j<this.grilla.ancho;++j)if(!(j==this.grilla.ancho-1&&isShort))b=new bubble(this),b.makeItRandom(),b.i=i,b.j=j,
b.dy=this.bubbleVelocity,this.grilla.Table[i][j]=b,b.recalcXY(),this.addBubble(b)}};this.addRandomRow=function(){ancho=this.grilla.ancho;newrow=Array(ancho);this.grilla.isShortRow(0)||(ancho--,newrow[ancho]="nada");this.grilla.alto=this.grilla.Table.unshift(newrow);for(var a=0;a<this.bubbles_array.length;++a)this.bubbles_array[a].i+=1;for(a=0;a<ancho;++a)b=new bubble(this),b.makeItRandom(),b.i=0,b.j=a,b.dy=this.bubbleVelocity,b.recalcXY(),newrow[a]=b,this.addBubble(b)}}
function gameUI(d,g){this.width=d;this.height=g;this.acumuledPoints=this.pointsCounter=this.points=0;this.savePoints=function(){this.acumuledPoints=this.points};this.restorePoints=function(){this.points=this.acumuledPoints};this.draw=function(d){d.save();d.fillStyle="#fff";d.fillRect(0,0,100,25);d.font="bold 12px sans-serif";d.fillStyle="#000";this.pointsCounter<this.points&&this.pointsCounter++;d.fillText(this.pointsCounter,10,10);d.restore()};this.addPoints=function(d){this.points+=d}}
function appEnviroment(d,g,f){this.canvas=document.getElementById(d);this.painter=document.getElementById(d).getContext("2d");this.menu=document.getElementById(g);this.backgroundImage=backgroundImage;this.clock=new Timeline(24);this.clock.connect(tick,"tick");switch(f){case "320x480":this.canvas.width=320;this.canvas.height=480;this.level=new bubbleLevel(240,400,10,20);break;case "360x480":this.canvas.width=360;this.canvas.height=480;this.level=new bubbleLevel(360,480,12,20);break;case "640x960":this.canvas.width=
640;this.canvas.height=960;this.level=new bubbleLevel(640,960,15,30);break;case "480x800":this.canvas.width=480;this.canvas.height=800;this.level=new bubbleLevel(480,800,13,25);break;case "854x480":this.canvas.height=480,this.canvas.width=854,this.level=new bubbleLevel(854,480,25,20)}this.cannon=new bubbleCannon(this.level);this.level.cannon=this.cannon;this.ui=new gameUI(this.canvas.width,this.canvas.height);this.mouseMove=function(){};this.mouseClick=function(a){game.cannon.shoot(a.clientX,a.clientY)};
this.startNewGame=function(){this.clock.start();this.menu.style.zIndex-=1};this.continueGame=function(){};this.showMenu=function(){clock.stop()};this.clearPainter=function(){this.painter.save();this.painter.clearRect(0,0,this.width,this.height);this.painter.restore()};this.drawCannon=function(){this.cannon.currentBubble!=null&&(this.painter.save(),this.painter.drawImage(this.cannon.currentBubble.meinBild,this.width/2,this.height-this.level.bubbleRadius),this.painter.restore())};this.drawBalls=function(){this.level.drawBalls(this.painter)};
this.drawBackground=function(){this.painter.save();this.painter.drawImage(this.backgroundImage,0,0);this.painter.drawImage(lvlFrame,(this.canvas.width-lvlFrame.width)/2,this.canvas.height-lvlFrame.height);this.painter.fillRect(this.level.leftBound,this.level.topBound,this.level.width,this.level.height);this.painter.restore()};this.draw=function(){this.clearPainter();this.drawCannon();this.drawBalls();this.ui.draw(this.painter)};this.startAnimation=function(){this.ui.points=this.level.points;this.level.moveBalls();
this.draw()};this.width=$("#"+d).width();this.height=$("#"+d).height();this.top=$("#"+d).offset().top;this.left=$("#"+d).offset().left;this.level.top=this.top;this.level.left=this.left;this.level.topBound=this.canvas.height-this.level.height;this.level.leftBound=(this.canvas.width-this.level.width)/2;this.level.makeMeRandom(5);this.cannon.setReadyShoot();$("#"+d).click(this.mouseClick)}function tick(){game.startAnimation()};